export const OPEN_TELEMETRY_SDK_INSTANCE = 'OPEN_TELEMETRY_SDK_INSTANCE';
export const OPEN_TELEMETRY_METRICS_API = 'OPEN_TELEMETRY_METRICS_API';
export const OPEN_TELEMETRY_TRACE_API = 'OPEN_TELEMETRY_TRACE_API';
